baseURL = 'https://snasello.github.io'
languageCode = 'en'
title = ''
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Samuel Nasello"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.fr]
title = "Samuel Nasello"
weight = 2
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Samuel Nasello"
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "bluesky",
  "linkedin",
  "x-twitter"
]

[params.ananke.social.follow]
networks = [
  "github",
  "bluesky",
  "linkedin",
  "x-twitter"
]

[params.ananke.social.github]
username = "snasello"

[params.ananke.social.linkedin]
username = "snasello"

[params.ananke.social.x-twitter]
username = "snasello"

[params.ananke.social.bluesky]
username = "snasello.bsky.social"